<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.10" />
        <PackageReference Include="Microsoft.Identity.Web" Version="4.13.2" />
        <PackageReference Include="Microsoft.Identity.Web.UI" Version="4.13.2" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.16.15" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DocuGuardAI.Application\DocuGuardAI.Application.csproj" />
      <ProjectReference Include="..\DocuGuardAI.Infrastructure\DocuGuardAI.Infrastructure.csproj" />
    </ItemGroup>

</Project>
